FROM python:3.6-jessie

RUN pip install numpy  \
    && pip install scipy==1.1.0  \
    && pip install flopy==3.2.9  \
    && pip install pika==0.12.0  \
    && pip install mystic==0.3.1  \
    && pip install scikit-learn==0.19.1  \
    && pip install deap==1.2.2
